javac BinaryFileReader.java
javac BinaryFileWriter.java
javac Canny.java
javac Converter.java
javac DoubleFileReader.java
javac Enhance.java
javac FileImage.java
javac MedianFilter.java
javac NeuralNetwork.java
javac Normalization.java
javac Perwitt.java
javac Smooth.java
javac Sobel.java
javac TextFilePrinter.java
javac TextFileReader.java
javac PGM256.java